version: '3'

services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-net
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - app-net
    depends_on:
      - mongodb
  mongodb:
    container_name: db
    image: mongo:latest
    expose:
      - 27017
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    networks:
      - app-net

networks:
  app-net:

volumes:
  mongo-db: